services:

  # App
  app:
    volumes:
      - '../../../scopa2-game:/var/www/scopa2-game'
    ports:
      - '6274:6274'
      - '6277:6277'
      - '${APP_PORT:-8000}:80'

  # MariaDB
  mariadb:
    ports:
      # Expose the port 3306 to the host
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'

volumes:
  mariadb:
    driver: local
